apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/devops-integrated/argocd-example-apps
    path: dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

