apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        env: dev
    spec:
      containers:
        - name: guestbook
          image: nginx:1.21
          ports:
            - containerPort: 80

