apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops-integrated/managed-argocd-lab
    targetRevision: HEAD
    path: guestbook-chart
    helm:
      values: |
        image:
          repository: nagadockeruser/guestbook
          tag: latest
          pullPolicy: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

