apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
spec:
  project: default
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/devops-integrated/argocd-example-apps
    path: prod
    targetRevision: HEAD
  syncPolicy: {}  # manual sync

